### ISSUE TITLE
reqOpenOrders in 981

### ISSUE THREAD

**Issue by misantroop** [quantrocket-llc/ibpythonic#5]
After updating to the most recent API and Gateway, reqOpenOrders has stopped sending a replies. Watching for all replies and there is none. Previously coming from 978 where the same code worked without issues. Any ideas where I should look for where the replies are handled?

**Comment by brian-from-quantrocket** [comment]
We're not yet running on 981 so I don't have any insights to offer. Please let us know if you figure something out.

**Comment by misantroop** [comment]
It appears to have been an issue on their side. It's working in 981.2r again.
